# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CimzMLParse <- function(xml_path) {
    .Call(`_Raman2imzML_CimzMLParse`, xml_path)
}

CimzMLStore <- function(fname, imgInfo) {
    .Call(`_Raman2imzML_CimzMLStore`, fname, imgInfo)
}

